"""AC vs TWAP on the locked synthetic market. Writes metrics.json and web/src/data.ts."""

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from execpath.ablate import ablation
from execpath.eval import evaluate, print_report

METRICS = "metrics.json"
DATA_TS = os.path.join("web", "src", "data.ts")


def main():
    m = evaluate()
    rows = ablation()
    hist = _hist(m["gaps"])
    out = {k: v for k, v in m.items() if k != "gaps"}
    out["ablation"] = rows
    out["gap_hist"] = hist
    with open(METRICS, "w") as f:
        json.dump(out, f, indent=2)
    print_report(m)
    print("ablation:")
    for r in rows:
        print(
            f"  {r['knob']}={r['value']:g}  success_pct {r['success_pct']:.1f}  "
            f"first-slice {100*r['first_share']:.1f}%"
        )
    write_data_ts(m, rows, hist)


def _hist(gaps, bins=12):
    import numpy as np

    g = np.asarray(gaps, float)
    counts, edges = np.histogram(g, bins=bins)
    return {
        "counts": counts.tolist(),
        "edges": [round(float(e), 4) for e in edges],
        "p10": float(np.percentile(g, 10)),
        "p50": float(np.percentile(g, 50)),
        "p90": float(np.percentile(g, 90)),
    }


def write_data_ts(m, rows, hist):
    if not os.path.isdir(os.path.dirname(DATA_TS)):
        return
    n = m["n_bins"]
    step = 4
    idx = list(range(0, n + 1, step))
    if idx[-1] != n:
        idx.append(n)
    x_ac = [round(m["x_ac"][i], 4) for i in idx]
    x_twap = [round(m["x_twap"][i], 4) for i in idx]
    x_dump = [1.0 if i == 0 else 0.0 for i in idx]
    t = [i / n for i in idx]
    ab = [
        {
            "knob": r["knob"],
            "value": r["value"],
            "success_pct": round(r["success_pct"], 1),
            "first_share": round(100 * r["first_share"], 1),
        }
        for r in rows
    ]
    payload = {
        "illustrative": False,
        "success_pct": round(m["success_pct"], 1),
        "n_win": m["n_win"],
        "n_paths": m["n_paths"],
        "n_bins": m["n_bins"],
        "eps": m["eps"],
        "lam": m["lam"],
        "mean_j_ac": round(m["mean_j_ac"], 3),
        "mean_j_twap": round(m["mean_j_twap"], 3),
        "mean_cost_ac": round(m["mean_cost_ac"], 3),
        "mean_cost_twap": round(m["mean_cost_twap"], 3),
        "mean_gap": round(m["mean_gap"], 3),
        "first_share_ac": round(100 * m["first_share_ac"], 1),
        "first_share_twap": round(100 * m["first_share_twap"], 1),
        "t": [round(v, 4) for v in t],
        "x_ac": x_ac,
        "x_twap": x_twap,
        "x_dump": x_dump,
        "ablation": ab,
        "gap_counts": hist["counts"],
        "gap_edges": hist["edges"],
        "gap_p10": round(hist["p10"], 3),
        "gap_p50": round(hist["p50"], 3),
        "gap_p90": round(hist["p90"], 3),
    }
    body = json.dumps(payload, indent=2)
    text = (
        "// Generated by scripts/run.py from the locked DESIGN protocol.\n"
        "export const ILLUSTRATIVE = false\n\n"
        f"export const DATA = {body} as const\n"
    )
    with open(DATA_TS, "w", encoding="utf-8") as f:
        f.write(text)


if __name__ == "__main__":
    main()
